name: CI-mac

on:
  - pull_request

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1

    - name: Install clang-format
      run: brew install clang-format

    - name: Configure
      run: cmake -Htest -Bbuild

    - name: Check format
      run: "! cmake --build build --target format"

    - name: Fix format
      run: cmake --build build --target fix-format

    - name: Check fixed format
      run: "cmake --build build --target format"

    - name: Check fixed format
      run: |
        "cmake --build build --target format
        ! git diff --exit-code"